### ISSUE TITLE
C-o doesn't work with use package declaration to set keybinding?

### ISSUE THREAD

**Issue by dandrake** [kickingvegas/casual-ibuffer#16]
I have casual-ibuffer configured with your suggested use-package, but the `C-o` keybinding doesn't work right away -- I think because of some lazy loading? When I first loaded ibuffer and did C-o, it opened the selected buffer. I tried `M-x casual-ibuffer-tmenu`, that worked -- and now `C-o` always does that in ibuffer.

Suggestions?

**Comment by kickingvegas** [comment]
@dandrake also, have you included `(require 'ibuffer)`?

**Comment by kickingvegas** [comment]
Also if others are seeing this issue, please chime in. Thanks!

**Comment by dandrake** [comment]
Using `(require 'ibuffer)` works.

I wasn't doing that before because it wasn't necessary -- I could just run ibuffer and it worked, with no "require" or otherwise. But adding that declaration fixes the issue. 

I tried  `(use-package ibuffer)` but then the lazy loading didn't just magically work, and this isn't a big enough deal for me to fiddle with `:after` or `:before` or whatever :)

**Comment by kickingvegas** [comment]
@dandrake thanks for confirming. Will amend the install instructions to include the `(require 'ibuffer)` statement.

**Comment by dandrake** [comment]
For what it's worth, I did eventually figure out how to do this just using `use-package`. 

(I don't know macros as well as I should, but I do understand that, since `use-package` is a macro that expands things into `require` declarations, for many simple cases, it's not a big deal to use one or the other. But I've gotten used to having everything as `use-package` and like being simple and consistent.)

The answer is, well, right in the manual: https://www.gnu.org/software/emacs/manual/html_node/use-package/Loading-sequentially.html

I currently have this, and it works as expected:

    (use-package ibuffer
      :defer t
      :hook (ibuffer-mode . hl-line-mode))
    
    (use-package casual-ibuffer
      :ensure t
      :defer t
      :after (ibuffer)
      :bind (:map ibuffer-mode-map
                  ("C-o" . casual-ibuffer-tmenu)
                  ("F" . casual-ibuffer-filter-tmenu)
                  ("s" . casual-ibuffer-sortby-tmenu)))

The key bit is the `:after` keyword, which it seems does exactly what it says!

**Comment by kickingvegas** [comment]
@dandrake Thanks for this configuration info! Will update the docs!
